<a href="https://colab.research.google.com/github/sujitdasnits/AIML-LAB/blob/main/Week_1_Assignement_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We will NumPy python Library and its various operations.
Introduction: 
1.   NumPy is a python Library used for working with arrays.
2.   NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference in computer science.
3. Syntax import numpy as np



In [ ]:
#import numpy and create 1-D array
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [ ]:
#numpy version 
print(np.__version__)

1.21.6


In [ ]:
#Check Type
print(a.dtype)
print(type(a))

int64
<class 'numpy.ndarray'>


In [ ]:
# 2-D and 3-D arrays
#2-D array
c = np.array([[1, 2, 3], [4, 5, 6]])
#3-D array
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
#check dimension
print('The dimension of array c:',c.ndim)
print('The dimension of array d:',d.ndim)
print('Display array c:\n', c)
print('Display array d:\n', d)

The dimension of array c: 2
The dimension of array d: 3
Display array c:
 [[1 2 3]
 [4 5 6]]
Display array d:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#byte size of each elements
print(c.itemsize)

8


In [ ]:
#size of numpy array
d.size

12

In [ ]:
#Shape of an array (Rows and columns)
c.shape

(2, 3)

In [ ]:
#Reshape
c_reshape = c.reshape(3,2)
print(c_reshape.shape)
print(c_reshape)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#Slicing: Extracting a particular set of elements from an array
print(c)
print(c[0:1, 0:2])


[[1 2 3]
 [4 5 6]]
[[1 2]]


In [ ]:
#Array Reshape 1D to 2D
ar_1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

ar_2D = ar_1D.reshape(4, 3)
print(ar_2D)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Array Reshape 1D to 3D
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements
ar_3D = ar_1D.reshape(2, 3, 2)
print(ar_3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#Array Join
# Join of 1D arrays
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
a_join = np.concatenate((a1,a2))
print(a_join)

[1 2 3 4 5 6 7 8]


In [ ]:
#Array Join
# Join of 2D arrays
a12 = np.array([[1, 2], [3, 4]])
a22 = np.array([[5, 6], [7, 8]])
a_join = np.concatenate((a12,a22), axis=1)
print(a_join)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Split the array
a_31 = np.array([1, 2, 3, 5])

a_31spli = np.array_split(a_31, 3)

print(a_31spli)

[array([1, 2]), array([3]), array([5])]


In [ ]:
#searching in an array
#print index of element 4
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [ ]:
#search where values are even
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)
y = np.where(arr%2 == 1)
print('Even values are present at:',x)
print('Odd values are present at:',y)

Even values are present at: (array([1, 3, 5, 7]),)
Odd values are present at: (array([0, 2, 4, 6]),)


In [ ]:
#Array Sort
arr = np.array([6,5,1,2,9,10,36,7])
sort_arr = np.sort(arr)
dec_sort = -np.sort(-arr)
print(' Ascending Sorted Array:',sort_arr)
print(' Descending Sorted Array:',dec_sort)

 Ascending Sorted Array: [ 1  2  5  6  7  9 10 36]
 Descending Sorted Array: [36 10  9  7  6  5  2  1]


In [ ]:
#Array sorting of 2D array
arr_2D = np.array([[5,3,7],[8,10,6],[40,-2,7]])
print(arr_2D)
sort_arr = np.sort(arr_2D)
dec_sort = -np.sort(-arr_2D)
print(' Ascending Sorted Array:',sort_arr)
print(' Descending Sorted Array:',dec_sort)

[[ 5  3  7]
 [ 8 10  6]
 [40 -2  7]]
 Ascending Sorted Array: [[ 3  5  7]
 [ 6  8 10]
 [-2  7 40]]
 Descending Sorted Array: [[ 7  5  3]
 [10  8  6]
 [40  7 -2]]


In [ ]:
#Random Number
#NumPy offers the random module to work with random numbers.
from numpy import random
#generate random integer
x = random.randint(100)
y =random.rand(1)
print(x)

79


In [ ]:
#Generate a 1-D array containing 5 random integers from 0 to 20:
x=random.randint(20, size=(5))
#Generate a 1-D array containing 5 random floats:
y = random.rand(5)
print(y)

[0.90158821 0.31767761 0.51938245 0.33658364 0.55967982]


In [ ]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
x = random.randint(100, size=(3, 5))
#Generate a 2-D array with 3 rows, each row containing 5 random numbers:
y = random.rand(3, 5)
print(y)

[[0.21372189 0.91099043 0.15868796 0.44529524 0.75954566]
 [0.10158759 0.89065379 0.76884486 0.66470926 0.35161469]
 [0.59308514 0.43673858 0.88368296 0.2330565  0.41428028]]


In [ ]:
'''Random Permutations of Elements
The NumPy Random module provides two methods for this: shuffle() and permutation()'''
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)
#The shuffle() method makes changes to the original array.

[4 3 5 1 2]


In [ ]:
#Generate a random permutation of elements of following array:
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))
#The permutation() method returns a re-arranged array (and leaves the original array un-changed).

[5 3 4 1 2]


In [ ]:
#Random Shuffle of 2D array
arr =np.array([[1,2, 3],[ 4,  5,  6],[ 7,  8,  9],[10, 11, 12]])
print(arr)
random.shuffle(arr)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [ 7  8  9]]
